version: '3.9'

services:
  server:
    build: ./server
    ports:
      - '3000:3000'
    volumes:
      - ./server:/app
    working_dir: /app
    command: npm run dev

  front:
    build: ./front
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
      - /app/node_modules
    working_dir: /app
    command: yarn dev --host
