version: '3.9'

services:
  server:
    build: ./server
    ports:
      - '3000:3000'
    volumes:
      - ./server:/app
    working_dir: /app
    command: npm run dev
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: app_development
    depends_on:
      - db

  front:
    build: ./front
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
      - /app/node_modules
    working_dir: /app
    command: yarn dev --host

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_development
      MYSQL_USER: app
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
